### ISSUE TITLE
파일의 시간을 받아오는 함수 filetime() 코드 리뷰

### ISSUE THREAD

**Issue by edoll1843** [kwnagho99/Assignment2#11]
//파일 1의 시간 정보를 가져오는 함수 작성
void filetime1(){
    time1 = localtime(&stat1.st_mtime);
    time1_ = *time1;
}
// time 변수에 localtime함수에 인자로 들어간 text1의 시간을 가져와 대입한다.

//파일 2의 시간 정보를 가져오는 함수 작성

void filetime2(){
    time2 = localtime(&stat2.st_mtime);
    time2_ = *time2;
}
// time 변수에 localtime함수에 인자로 들어간 text2의 시간을 가져와 대입한다.

**Comment by kwnagho99** [comment]
localtime이 tm구조체에 내장된 함수군요
