### ISSUE TITLE
파일의 시간을 받아오는 함수 filetime() 기술 조사

### ISSUE THREAD

**Issue by edoll1843** [kwnagho99/Assignment2#12]
#include <time.h>헤더를 추가하여 진행하였다.
시간 구조체는 다음과 같다.
struct tm *localtime(const time_t*timep);
const time_t* timep : time_t형 변수를 가리키는 포인터 
 struct tm* localtime : 시간 정보가 들어가는 구조체 포인터

struct tm { 
int tm_sec; /* seconds */
 int tm_min; /* minutes */
 int tm_hour; /* hours */
 int tm_mday; /* day of the month */
 int tm_mon; /* month */
 int tm_year; /* year */
int tm_wday; /* day of the week */
int tm_yday; /* day in the year */ 
int tm_isdst; /* daylight saving time */ 
}

**Comment by kwnagho99** [comment]
tm_min, tm_hour, tm_mon, tm_mday 변수만 활용하면 되겠네요
