### ISSUE TITLE
파일 수정 날짜(월/일) 비교 함수 datecmp() 코드 리뷰

### ISSUE THREAD

**Issue by edoll1843** [kwnagho99/Assignment2#14]
void datecmp() {
    printf("date compare\n");
    if (time1_.tm_mon + 1 < time2_.tm_mon + 1)
        printf("text1 is early\n");
    else if (time1_.tm_mon + 1 > time2_.tm_mon + 1)
        printf("text2 is early\n");
    else
    {
        if (time1_.tm_mday < time2_.tm_mday)
            printf("text1 is early\n");
        else  if (time1_.tm_mday > time2_.tm_mday)
            printf("text2 is early\n");
        else
            printf("same date\n");
    }
    printf("\n");
}
text1을 담은 time1_과 text2를 담은 time2_의 변수를
시간 구조체를 사용하여 비교하였다.
tm_mon을 기준으로 각 text를 비교하고 만약 같다고 하면
tm_mday를 비교하여 어떤 파일이 더 늦게 수정하였는지 그에 맞는
코멘트를 출력해준다. 만약 같다면 같다는 코멘트를 출력한다.

**Comment by kwnagho99** [comment]
조건문이 효율적으로 잘 짜여진 것 같네요
