### ISSUE TITLE
파일 수정 시간(시/분) 비교 함수 timecmp() 코드 리뷰

### ISSUE THREAD

**Issue by edoll1843** [kwnagho99/Assignment2#16]
void timecmp() {
    printf("time compare\n");

    if (time1_.tm_hour < time2_.tm_hour)

        printf("text1 is early\n");

    else if (time1_.tm_hour > time2_.tm_hour)

        printf("text2 is early\n");
    else

    {
        if (time1_.tm_min < time2_.tm_min)

            printf("text1 is early\n");

        else if (time1_.tm_min > time2_.tm_min)

            printf("text2 is early\n");

        else
            printf("same time\n");
    }
    printf("\n");
}
역시 시간 구조체를 통해 비교를 진행하였다.
tm_hour로 시간을 비교한다. 만약 같다면
tm_min으로 수정 된 분을 비교하여 코멘트를 출력한다.
만약 같다면 그에 맞는 코멘트를 출력한다.

**Comment by kwnagho99** [comment]
이전 함수처럼 잘 작동하겠네요
