### ISSUE TITLE
filestat 함수 기술조사

### ISSUE THREAD

**Issue by kwnagho99** [kwnagho99/Assignment2#17]
"sys/stat.h" 헤어파일에 정의된 stat 구조체가 있다.
stat 구조체에는 파일의 id, inode number, 하드링크 수, user id, group id , 파일 최종 수정시간 등의 파일정보가 들어가있다.
struct stat*형으로 선언된 구조체 포인터로 원하는 파일명의 멤버를 호출할 수 있다.
struct stat { 
dev_t st_dev; /* ID of device containing file */ 
ino_t st_ino; /* inode number */ 
mode_t st_mode; /* protection */ 
nlink_t st_nlink; /* number of hard links */ 
uid_t st_uid; /* user ID of owner */ 
gid_t st_gid; /* group ID of owner */ 
dev_t st_rdev; /* device ID (if special file)
off_t st_size; /* total size, in bytes */ 
blksize_t st_blksize; /* blocksize for file system I/O */ 
blkcnt_t st_blocks; /* number of 512B blocks allocated */ 
time_t st_atime; /* time of last access */ 
time_t st_mtime; /* time of last modification */ 
time_t st_ctime; /* time of last status change */ };

**Comment by edoll1843** [comment]
참고 하여 진행 하겠습니다.
