### ISSUE TITLE
sizecmp 함수 리뷰

### ISSUE THREAD

**Issue by kwnagho99** [kwnagho99/Assignment2#20]
if (stat1.st_size > stat2.st_size)
        printf("text1 is bigger\n");

    else if (stat1.st_size < stat2.st_size)
        printf("text2 is bigger \n");

    else if (stat1.st_size == stat2.st_size)
        printf("sizes are equal\n");

두 파일의 크기가 위 조건문에의해 잘 비교되었습니다.

**Comment by edoll1843** [comment]
참고하겠습니다.
