### ISSUE TITLE
blockcmp 함수 리뷰

### ISSUE THREAD

**Issue by kwnagho99** [kwnagho99/Assignment2#22]
void blockcmp(){
    printf("block compare\n");
    if (stat1.st_blocks > stat2.st_blocks)
        printf("text1 is bigger\n");

    else if (stat1.st_blocks < stat2.st_blocks)
        printf("text2 is bigger\n");

    else if (stat1.st_blocks == stat2.st_blocks)
        printf("blocks are equal\n");
    printf("\n");
}
구조체 변수에 block size가 저장된 후 위 조건문을 통해 크기비교가 올바르게 이루어 졌습니다

**Comment by edoll1843** [comment]
참고하겠습니다.
