### ISSUE TITLE
파일 크기비교 함수 sizecmp() 코드 작성

### ISSUE THREAD

**Issue by kwnagho99** [kwnagho99/Assignment2#6]
void sizecmp(){
		printf("size compare\n");
	if (stat1.st_size > stat2.st_size)
		printf("text1 is bigger\n");

	else if (stat1.st_size < stat2.st_size)
		printf("text2 is bigger \n");

	else if (stat1.st_size == stat2.st_size)
		printf("sizes are equal\n");

printf("\n");
}

**Comment by edoll1843** [comment]
고생하셨어요

**Comment by kwnagho99** [comment]
구현 완료했습니다. kwangho branch도 delete 했습니다
